<template id="">
  <div id="blog" class="">
    <h2 class="center">Blog Section</h2>
    <div class="divider teal"></div>
    <h4 class="red-text center">Coming Soon!</h4>
  </div>
</template>

<script type="text/javascript">
  export default {
    name: 'Blog',
    data() {
      return {

      }
    }
  }
</script>

<style media="screen">
  #blog .divider {
    width: 50%;
    margin-left: 25%;
  }
</style>
