<template>
  <div id="visualization" class="center">
    <h2>Visualization Page</h2>
    <div class="divider teal"></div>
    <h4 class="red-text">Coming Soon!</h4>
  </div>
</template>

<script type="text/javascript">
  export default {
    name: 'Visualization',
    data() {
      return {

      }
    }
  }
</script>

<style media="screen">
  #visualization .divider {
    width: 50%;
    margin-left: 25%;
  }
</style>
